server:
  servlet:
    context-path: /api/v1

spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${SPRING_ACTIVE_PROFILES}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_MAIL_USERNAME}
    password: ${GMAIL_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET}

app:
  base-url: ${BASE_URL}
  client-url: ${CLIENT_URL}
