server:
  servlet:
    context-path: /api/v1

spring:
  config:
    import: file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/financeManager
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_SECRET}
