server:
  servlet:
    context-path: /api/v1

spring:
  config:
    import: file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/financeManager
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_MAIL_USERNAME}
    password: ${GMAIL_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET}

app:
  base-url: http://localhost:8080/api/v1/
  client-url: http://localhost:8080/api/v1/
