server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financeManager
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
